name: nih2mne-tests
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - name: Setup git repo python
        run: make install_test      
      - name: Check FS Cache
        id: cache-fsdownload
        uses: actions/cache@v3
        with:
          path: ~/FSData
          key:
            FSData.tar.gz
      - if: ${{ steps.cache-fsdownload.outputs.cache-hit != 'true' }}
        run: pip install gdown; gdown --folder ${{ secrets.GDRIVE_MRI }} -O ~/FSData
      - name: Pytest
        run: make test
